#!/usr/bin/perl -w
use Socket;
use Sys::Hostname;
use strict;

my($file) = @ARGV;
my($hostaddr);   # struct sockaddr_in
my $rin = "";

open(FILE,$file) or die $!; $file = join('',<FILE>); close(FILE);

$|=1;

vec($rin,fileno(STDIN),1) =1;
if (select($rin,undef,undef,15)) {
  my($foo);
  $hostaddr = recv(STDIN,$foo,10,0) or die $!;
  send(STDOUT,$file,0,$hostaddr) or die $!;
}
