#!/usr/bin/perl
use Socket;
use Sys::Hostname;
use strict;

my($host,$port) = @ARGV;
my($hostaddr);   # struct sockaddr_in
my($proto);
my $rin = "";
my($raw);

$proto = getprotobyname('udp') or die $!;
if ($port+0 ne $port) { $port = getservbyname($port,'udp') or die $!; }
socket(SOCKFD, AF_INET, SOCK_DGRAM, $proto) or die $!;
bind(SOCKFD, sockaddr_in(0,inet_aton(hostname()))) or die $!;
# Send two, one for inetd, one for the program itself
send(SOCKFD,"GIMME IT!!",0,sockaddr_in($port,inet_aton($host))) or die $!;

$|=1;

vec($rin,fileno(SOCKFD),1) =1;
if (select($rin,undef,undef,15)) {
  ($hostaddr = recv(SOCKFD,$raw,4096,0)) or die $!;
  print $raw;
}
